target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'core', :path => '../shared/core'
  pod 'local', :path => '../shared/data/local'
  pod 'remote', :path => '../shared/data/remote'
  pod 'poirepository', :path => '../shared/feature/poi/poirepository'
  pod 'poiui', :path => '../shared/feature/poi/poiui'
  pod 'homeui', :path => '../shared/feature/home/homeui'
end