target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'

  pod 'KMPNativeCoroutinesCombine'

  pod 'core', :path => '../shared/core'
  pod 'local', :path => '../shared/data/local'
  pod 'remote', :path => '../shared/data/remote'
  pod 'poi', :path => '../shared/feature/poi'
  pod 'poilistvm', :path => '../shared/ui/logic/poilistvm'
end